### ISSUE TITLE
Issues with recent firmware on Edge 1030

### ISSUE THREAD

**Issue by Pcb21** [to-ko/EveryTile#1]
I posted this is a review in the ConnectIQ app store, but figured it won't do any harm to repost here.

===

Hi Tomasz,

Thank you for writing this great app! I found the same as the other two - it (version 1.1.5) was not working once the latest firmware had been pushed to my Edge 1030.

HOWEVER - and this a big thank you to you for opening the source - if I recompile the app against the latest SDK (3.0.x) it DOES work for me (I re-uploaded a beta version of a new app called "RideEveryTile").

Would you be interested in regenerating the app against a new SDK? Alternatively should I try to publish the version I compiled? 

Thanks, Pete

**Comment by to-ko** [comment]
Hi Pete,

thanks a lot! I'll recompile and push an update to the app store...

cheers,
Tomasz
